### ISSUE TITLE
New configuration schema

### ISSUE THREAD

**Issue by fwinkelbauer** [fwinkelbauer/Bumpy#37]
This is a suggestion for a major **breaking change**.

The current `.bumypconfig` file uses an `.ini`style configuration which I would like to change because:

- For the most part it is an invalid `.ini` file
- I want to be able to extend the configuration in the future in an easy manner
  - Support for XML and Regex matching
  - Multiline versions in XML (issue #30)
  - ???

I have toyed around with several formats, but they all have their downsides:

- **YAML:** I was rather unfamiliar with the format. It took me quite a while to figure something out that might work
- **JSON:** Regular expressions containing `"` have to be escaped
- **XML:** Even more characters have to be escaped (`<, >, ", ...`)
- **Valid INI:** Does not offer the configuration capabilities that I am looking for. It could work, but parts of it seem hacky

Dealing with escape characters is the biggest downside in my opinion. Even though I would like to use an `ini` style configuration (just to be similar to [editorconfig](http://editorconfig.org/)), I am currently considering a `yaml` format. Here are a few examples:

```yaml
# .NET Core
- glob: "*.csproj"
  encoding: utf-8
  xml:
  - profile: info
    query: # these XML elements get combined into one (would be a new feature)
    - Project/PropertyGroup/VersionPrefix
    - Project/PropertyGroup/VersionSuffix
  - query: Project/PropertyGroup/Version

# .NET Framework
- glob: "AssemblyInfo.cs"
  regex:
  - profile: assembly
    query: (?<marker>Assembly(File)?Version).*(?<version>\d+\.\d+\.\d+\.\d+)
  - profile: info
    query: (?<marker>AssemblyInformationalVersion).*(?<version>\d+\.\d+\.\d+\.\d+)

# Other examples

# Using templates (which are already in Bumpy 0.10.0)
- glob: "NuSpec/**/*.nuspec"
  inherit_template: true

# Using templates while overriding elements (not possible in Bumpy 0.10.0)
- glob: "NuSpec/**/*.nuspec"
  inherit_template: true
  encoding: utf-8
```

@mwallner @euronay does anyone have another idea/suggestion?
